### PR TITLE
Fixes cleancss -O0 some.css not work

### PR DESCRIPTION
**Pull request by cooliean**
Fixes https://github.com/clean-css/clean-css-cli/issues/80

### CODE REVIEW

**Comment by cooliean** [comment]
[Fixes cleancss -O0 some.css not work](https://github.com/clean-css/clean-css-cli/issues/80)

**Comment by SuperStormer** [comment]
@jakubpawlowicz bumping this PR

**Comment by jakubpawlowicz** [comment]
Hey @cooliean @SuperStormer - happy to merge it as long as it passes all tests. Last time I pulled a PR and noticed it's slightly more complex case (thus failing tests). Anyone interested to figure it out?

**Comment by jakubpawlowicz** [comment]
Fixed in #86.

**Pull request closed without merging**
